// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdsQJO3iny2Hx0i9pB-l_qDBarT8p37NI',
    appId: '1:276270791184:web:d56d4fbd3d453a455e6895',
    messagingSenderId: '276270791184',
    projectId: 'mabasa-job-app',
    authDomain: 'mabasa-job-app.firebaseapp.com',
    storageBucket: 'mabasa-job-app.appspot.com',
    measurementId: 'G-588GMTTK1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkLVZU7Ib2ceB9lkvZ1eiuQK9GsnQiSiE',
    appId: '1:276270791184:android:37951e3d9844810d5e6895',
    messagingSenderId: '276270791184',
    projectId: 'mabasa-job-app',
    storageBucket: 'mabasa-job-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsQJO3iny2Hx0i9pB-l_qDBarT8p37NI',
    appId: '1:276270791184:ios:your_ios_app_id',
    messagingSenderId: '276270791184',
    projectId: 'mabasa-job-app',
    storageBucket: 'mabasa-job-app.appspot.com',
    iosBundleId: 'com.zinosoftware.mabasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdsQJO3iny2Hx0i9pB-l_qDBarT8p37NI',
    appId: '1:276270791184:ios:your_macos_app_id',
    messagingSenderId: '276270791184',
    projectId: 'mabasa-job-app',
    storageBucket: 'mabasa-job-app.appspot.com',
    iosBundleId: 'com.zinosoftware.mabasa',
  );
}
