# Generated by Django 5.0.6 on 2025-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Accountancy', 'Accountancy'), ('Administration', 'Administration'), ('ICT', 'ICT'), ('Manufacturing', 'Manufacturing'), ('HR', 'HR'), ('Sales', 'Sales'), ('Logistics', 'Logistics')], max_length=64),
        ),
    ]
